config/routes.rb
Rails.application.routes.draw do
  resources :reports
  mount Upmin::Engine => '/kayslegion'

  get 'groups/profile'
  get 'users/profile'
  get 'roster', to: 'roster#index'
  get 'playground', to: 'visitors#playground'
  get 'eval_gen', to: 'users#eval_gen'
  get 'phone_gen', to: 'users#phone_gen'
  get 'avatar_gen', to: 'users#avatar_gen'
  get 'avail_gen', to: 'users#avail_gen'
  get 'desc_gen', to: 'users#desc_gen'
  get 'gen', to: 'users#gen'
  post 'courses/csv_import'


  devise_for :users, :controllers => {:registrations => "registrations"}
  root :to => "visitors#index"

  resources :users do
    member do
      get :registrations
      get :sessions
      post :set_current_course
      post :set_current_project
    end
    collection do
      get :desc_gen
      get :avail_gen
      get :avatar_gen
      get :phone_gen
      get :eval_gen
      get :gen

      get :export_ungrouped
      get :export_groups
    end
  end

  resources :groups do
    member do
      get :edit
      post :update
      get :remove
      get :leave
      get :request_join
      get :send_request
      get :disband
      get :show
      get :update
      get :confirm
      post :update_relation
    end
    collection do
    end
  end

  resources :courses do
    member do
      get :edit
      get :show
      post :update

    end
    collection do
      get :csv_import
    end
  end

  resources :projects do
    member do
      get :edit
      post :update
      get :remove
      get :reduce_groupsize
      get :show
      get :increase_groupsize
      get :autogroup
      post :autogroup
      get :clear_partnerships
      post :set_current_project
    end
    collection do
    end
  end

  resources :grouprelations do
    member do
      get :edit
      post :update
      get :remove
    end
    collection do
    end
  end
  resources :evaluations do
    member do
      get :edit
      post :update
      get :remove
    end
    collection do
      get :export_evals
      get :export_eval_summary
    end
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "sign_out", to: "devise/sessions#destroy"
    get "edit", to: "devise/registrations#update"
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  helper_method :teammates?, :in_group_for?, :classmates?
  include UsersHelper, GroupsHelper

  def index
    @users = User.all
    if user_signed_in?
      set_current_users_instance_variables
    
	current_user.groups.order(:project_id).uniq.each do |group| 
		@is_current_user_requested = (group.group_relations.find_by(user_id: current_user.id, group_id: group.id).status == 1) if group.group_relations.find_by(user_id: current_user.id, group_id: group.id) 
	 	@is_current_user_confirmed = (group.group_relations.find_by(user_id: current_user.id, group_id: group.id).status == 2) 
	 	@are_there_any_users_sending_requests = (group.group_relations.find_by(status: 0) != nil) 
	end 
end
 end
end

app/views/visitors/_mygroups.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title"><span class="glyphicons glyphicons-notes-2"></span>&emsp;&emsp;Current Groups</h2>
  </div>
  <div class="panel-body" style= "<%= 'padding:1px;' if !current_user.groups.empty?%>">
	<%if current_user.groups.empty? %>
			<span style="font-weight:bold">Sorry, you don't have any groups yet!</span>
	<% else %>
	  <% current_user.groups.each do |group| %>
			<center>
		  		<% @group = group%>
					<%= render 'groups/profile', group: @group %><br>
			</center>
  	<% end %>
	<% end %>
</div>
</div>

 

app/views/visitors/_notification_professor.html.erb
<% if course.projects.empty?%>
    <div style= "text-align:left;white-space:normal;margin:4px;", class= "btn alert-danger" data-toggle="modal" data-target="#create-<%= course.id%>">
      <span class="glyphicons glyphicons-warning-sign"></span>
      <span style="font-size:18px;">&ensp;Alert:</span></span>
      <span style="font-size:13px;">There is no active project for <%= course.course_title %>.<br>
        Students are not able to partner up.</span></div><% @notifications = true %>
    <%= render template: "projects/modals/new-project", locals: {course: course}%>
<% end %>

app/views/visitors/_notification_student.html.erb
<% current_user.groups.order(:project_id).uniq.each do |group| %>
    <% @is_current_user_grouped = !group.group_relations.find_by(user_id: current_user.id, group_id: group.id).nil?%>
    <% @is_current_user_requested = (group.group_relations.find_by(user_id: current_user.id, group_id: group.id).status == 1) if group.group_relations.find_by(user_id: current_user.id, group_id: group.id)%>
    <% @is_current_user_confirmed = (group.group_relations.find_by(user_id: current_user.id, group_id: group.id).status == 2) if group.group_relations.find_by(user_id: current_user.id, group_id: group.id)%>
    <% @are_there_any_users_sending_requests = (group.group_relations.find_by(status: 0) != nil) %>


<% if ((@is_current_user_requested) || (@is_current_user_confirmed && @are_there_any_users_sending_requests)) %>
<!-- checking if group's name is nil, make one for them -->
<% group.name != nil ? groupname = group.name : groupname = group.users.pluck(:first_name).to_sentence %>
  <div style='text-align:right;'>
      <hr style="margin-top:7px;margin-bottom:3px;">
      <span style="font-size:25px; float:left;font-weight:bold;"> <%= link_to groupname, group %></span>
      <%=  link_to "<span class=\"glyphicons glyphicons-handshake\"></span>&nbsp;&nbsp;<b>Accept</b>".html_safe, confirm_group_path(group),  class: "btn btn-primary btn-sm" %>
    <%= link_to "<span class=\"glyphicons glyphicons-remove\"></span>&nbsp;&nbsp;<b>Deny</b>".html_safe, leave_group_path(group), data: { confirm: "Are you sure you want to leave the group #{group.name}?"},  class: "btn btn-danger btn-sm" %>
  </div>
  <hr style="margin-top:7px;margin-bottom:3px;">
  <% members = group.users.order(:last_name).uniq %>
  <span style="font-weight:bold;font-size:13px;"> 
  Project:</span>
  <span style="font-size:12px;"> <%= group.project.name %></span>
  <span style="font-size:13px;font-weight:bold;">  <br>
  Course:</span>
  <span style="font-size:12px;"> <%= group.project.courses[0].course_title %><br>
  </span>
  <table class="table">
    <td><strong>Name</strong></td>
    <td><strong>Status</strong></td>
      <% members.each do |user| %>
        <% if GroupRelation.find_by(user_id: user.id, group_id: group.id).status == 2 %>
        <tr>
          <td><%= link_to "#{user.first_name} #{user.last_name}", user %></td>
          <td style="font-size:13px;">Confirmed</td>
        </tr>
        <% elsif GroupRelation.find_by(user_id: user.id, group_id: group.id).status == 1 %>
        <tr style= "background-color:eee; opacity: 0.6;">
          <td> <%= link_to "#{user.first_name} #{user.last_name}", user %></td>
          <td style="font-size:13px;">Request Sent</td>
        </tr>
        <% else %>
        <tr style= "background-color:eee; opacity: 0.6;">
          <td> <%= link_to "#{user.first_name} #{user.last_name}", user %></td>
          <td style="font-size:13px;">Sent Request</td>
        </tr>
        <% end %>
      <% end %>
  </table>
  <% end %>
<% end %>

app/views/visitors/_notifications.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title"><span class="glyphicons glyphicons-circle-exclamation-mark"></span>&emsp;&emsp;Notifications</h2>
  </div>
 

<% @notifications = false %>
<% case current_user.role %>
<% when 0 %>
 <div class="panel-body">
			<%= render 'visitors/notification_student' %>
<% when 1..3 %>
 <div class="panel-body">
   		<% current_user.courses.each do |course| %>
		<%= render 'visitors/notification_professor', course: course %>
		<% end %> 
	<% if @notifications == false %>
		<p>You don't
	    have any new notifications</p>
	<% end %>
<% end %>

  </div>
</div>

app/views/visitors/_professor_alerts.html.erb
	<% if course.projects.empty?%>
	<div class="content-box"><h3 style="font-size:20px; padding:5px;font-weight:bold;"><center><%= link_to course.course_title, projects_path %></center></h3>
		 <%=  link_to (new_project_path(id: course)), style: "color:#fff; text-align:left; padding:10px;white-space: normal;", class: "btn btn-danger" do %><span style="font-weight:bold;"><span class="glyphicons glyphicons-warning-sign" style="font-size:18px; line-height:1.5"></span><span style="font-size:18px; line-height:2">&ensp;Alert:</span><br></span><span style="font-size:13px;">There is no active project for this course.<br>Students are not able to partner up.<%@notifications = true%><% end %></span>
	</div>
	<%end%>

app/views/visitors/_signin_link.html.erb
<div class="jumbotron", style="padding:20px;background-image: none; text-align:center;">
<% if @ucinetid.blank? %>
<p style="font-size:12px">
You are not signed in to Webauth.
</p>

<%= link_to (request.ip == "127.0.0.1") ? "" : "https://login.uci.edu/", class:"btn btn-primary" do %>
		<span class="glyphicons glyphicons-log-in"></span> Login to WebAuth
		<% end %>
<% if request.ip == "127.0.0.1" %>
	<%= render "visitors/signin_select" %>
<% end %>
<% else %>
<p style="font-size:12px">
You are signed in to Webauth as <b><%= @ucinetid%></b><br>If this is incorrect, <a targer="blank" href="http://login.uci.edu/ucinetid/webauth_logout">click here to logout</a></p>
	<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    	<%= f.hidden_field :ucinetid, value: @ucinetid %> 
    	<%= f.submit "Login as... #{@ucinetid}", class:"btn btn-primary" %>
	<% end %>
<% end %>
</div>

app/views/visitors/_signin_select.html.erb
<div class="jumbotron", style="max-width: 350px; padding:23px;background-image: none;">
  <%= form_for(resource, as: resource_name, url: user_session_path, html: { role: 'form'}) do |f| %>
    <h3>Sign in As...</h3>
    <%= devise_error_messages! %>
		<% if request.ip == "127.0.0.1" || true %>
		<%users = User.all%>
			<%= f.select :id, options_for_select(users.collect {|p| [ p.first_name + " " + p.last_name + " - ID: " + p.id.to_s, p.id ]}), {}, 
				{class: 'form-control', style: 'width:70%; display:inline; height:29px;', onchange: 'this.form.submit();' } %>
	 	<% else %>
		  <%= f.hidden_field :id, value: @campus_id %> 
		  <%= f.hidden_field :ucinetid, value: @ucinetid %>
		<% end %>
		<%= f.submit 'Sign in', class: 'btn btn-primary' %>
		</div>
	<%end%>

app/views/visitors/_to_dos.html.erb
<div class="panel panel-primary" >
  <div class="panel-heading">
    <h2 class="panel-title">
    	<%= (current_user.role!=0) ? (render 'visitors/welcomemsg') : "<span class=\"glyphicons glyphicons-notes-2\"></span>&emsp;&emsp;To-Dos".html_safe%></h2>
  </div>
  

<% @notifications = false %>
<% case current_user.role %>
<% when 0 %>
		<%= render 'visitors/todos_student'%>
<% when 1..3 %>
		<%= render 'visitors/todos_professor'%>
<% end %>
</div></div>

app/views/visitors/_todos_student.html.erb
<div class="panel-body">
	<% current_user.courses.each do |course| %>
	<% course.projects.each do |project| %>
	<% if !project.partnership_deadline.nil? && !project.evaluation_deadline.nil? %>
		<h4><%= project.name%></h4>
			<% if project.partnership_deadline > Date.today %>
				The partnership deadline for <%= project.name %> is coming on <%= project.partnership_deadline.strftime("%m/%d/%y") %>
				<hr style="margin:5px;">
			<% elsif project.evaluation_deadline > Date.today %>
				The evaluation deadline is coming on <%= project.evaluation_deadline.strftime("%m/%d/%y") %>, You have <%= (project.evaluation_deadline - Date.today).to_i %> days left
				<hr style="margin:5px;">
			<% else %>
			    Looks like you're all caught up!
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/visitors/_userwelcomemsg.html.erb
<h1> Help</h1><p style="text-indent:2em;">To partner: Navigate to "Find a partner" on the nav bar and locate your desired partner's name. 
If you wish you may view a partner's info. Click on their email address to view their profile page. You can see their picture, and last login time to give you an idea if their account is still active. 
Click on "Request Partner" button in your partners table row to the right of their name to partner. 
To verify you have the right person, you can navigate to "Find a partner" or "Home" and both will notify you of your current partner status and their name.<br><br></p>

<p style="text-indent:2em;">To remove partner: The "Find a partner" page will change when you have a partner to "Undo".  This button will remove the partnership between the two of you if you clicked on the wrong person or need to change partners.<br><br></p>

Unable to partner? To report Bugs email us at xyz@uci.edu. or go to URL.com/bug

app/views/visitors/_welcomemsg.html.erb
<div class="jumbotron">

	<center><h2>Welcome to <br><img src="/assets/PartnerUpLogoBlue.png" style="max-width:75%;"></h2>

	<h4>UCI's premier partnering service. </h4></center>
	
</div>

app/views/visitors/index.html.erb
<% if user_signed_in? %>
  <div class="col-sm-4">
    <!-- pending requests/notifications here-->
    <%= render "visitors/notifications"%>
  </div>
  <div class="col-sm-8">
    <% case current_user.role %>
    <% when 0 %>
    <%= render 'visitors/to_dos'%>
    <%= render 'visitors/mygroups'%>
    <!-- if the user is a Professor or a T/A -->
    <% when 1..2 %>
      <%= render 'visitors/to_dos'%>
      <!-- if the user is an admin -->
      <% when 3 %>
    <% end %>
  <% else %>
  <% if @ucinetid && !user_signed_in? && request.headers["HTTP_REFERER"].blank?%>
     <%= render 'visitors/signin_link'%>
     <script>document.getElementById('new_user').submit();</script>
  <% end %>
    <div class="col-sm-8" style="text-align:center;">
      <%= render "visitors/welcomemsg" %>
    </div>
   <div class="col-sm-4">
      <%= render 'visitors/signin_link'%>
  </div>
  
 
  <% end %>

app/views/visitors/playground.html.erb
<%= link_to '#', class: "info-popover", title: "How to populate class data?", data: { content: "<b>hello popover world</b>", trigger: 'hover', delay: 500} do %>
	<span class="glyphicons glyphicons-circle-info"></span>
<% end %>

<%= link_to '#', class: "btn btn-lg btn-danger info-popover", title: "How to populate class data?", data: { content: "<b>hello popover world</b>" } do %>Indissmissable Popup
<% end %>

<!-- Button trigger modal -->
<%= link_to 'Add a New Project', '#', class: 'btn btn-primary btn-lg', data: { toggle: 'modal', target: '#myModal'}%>

<!-- Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a New Project</h4>
      </div>
      <div class="modal-body">
				HELLO!!
			
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       	<button type="button" class="btn btn-default" data-dismiss="modal">Submit</button>
      </div>
    </div>
  </div>
</div>


<!-- Button trigger modal -->
<%= link_to 'Upload Roster', '#', class: 'btn btn-primary btn-lg', data: { toggle: 'modal', target: '#upload-roster'}%>

<!-- Modal -->
<div class="modal fade" id="upload-roster">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a New Project</h4>
      </div>
      <div class="modal-body">
				HELLO!!
			
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       	<button type="button" class="btn btn-default" data-dismiss="modal">Submit</button>
      </div>
    </div>
  </div>
</div>


<% current_user.courses.each do |course| %>
  
  <%= link_to set_user_current_course_course_path(course.id), class:"btn btn-primary" do %>
    <span class="glyphicons glyphicons-group"></span> Find a Group
  <% end %>


<% end %>