config/routes.rb
Rails.application.routes.draw do
  resources :reports
  mount Upmin::Engine => '/kayslegion'

  get 'groups/profile'
  get 'users/profile'
  get 'roster', to: 'roster#index'
  get 'playground', to: 'visitors#playground'
  get 'eval_gen', to: 'users#eval_gen'
  get 'phone_gen', to: 'users#phone_gen'
  get 'avatar_gen', to: 'users#avatar_gen'
  get 'avail_gen', to: 'users#avail_gen'
  get 'desc_gen', to: 'users#desc_gen'
  get 'gen', to: 'users#gen'
  post 'courses/csv_import'


  devise_for :users, :controllers => {:registrations => "registrations"}
  root :to => "visitors#index"

  resources :users do
    member do
      get :registrations
      get :sessions
      post :set_current_course
      post :set_current_project
    end
    collection do
      get :desc_gen
      get :avail_gen
      get :avatar_gen
      get :phone_gen
      get :eval_gen
      get :gen

      get :export_ungrouped
      get :export_groups
    end
  end

  resources :groups do
    member do
      get :edit
      post :update
      get :remove
      get :leave
      get :request_join
      get :send_request
      get :disband
      get :show
      get :update
      get :confirm
      post :update_relation
    end
    collection do
    end
  end

  resources :courses do
    member do
      get :edit
      get :show
      post :update

    end
    collection do
      get :csv_import
    end
  end

  resources :projects do
    member do
      get :edit
      post :update
      get :remove
      get :reduce_groupsize
      get :show
      get :increase_groupsize
      get :autogroup
      post :autogroup
      get :clear_partnerships
      post :set_current_project
    end
    collection do
    end
  end

  resources :grouprelations do
    member do
      get :edit
      post :update
      get :remove
    end
    collection do
    end
  end
  resources :evaluations do
    member do
      get :edit
      post :update
      get :remove
    end
    collection do
      get :export_evals
      get :export_eval_summary
    end
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "sign_out", to: "devise/sessions#destroy"
    get "edit", to: "devise/registrations#update"
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_one :course, :through =>:group_relations
  has_one :project, :through=> :group_relations
  has_many :users, :through => :group_relations
  belongs_to :course
  belongs_to :project
  belongs_to :user
  has_many :group_relations
  has_many :evaluations, :through => :eval_relations
  belongs_to :evaluation
  has_many :eval_relations
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include UsersHelper, GroupsHelper
  helper_method :teammates?, :in_group_for?, :classmates?
  # before_filter :authenticate_user!
  # after_action :verify_authorized
  require 'csv'

  def index
    set_current_users_instance_variables
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update_relation
    user = User.find_by_id(params[:id])
    if !params[:group][:old].nil?
      relation = GroupRelation.find_by(project_id: current_user.current_project, user_id: params[:id])
      oldgroup = Group.find_by_id(params[:group][:old])
      newgroup = Group.find_by_id(params[:group][:id])
      relation.group_id = params[:group][:id]
      if relation.save
        if oldgroup.users.empty?
          oldgroup.destroy
        end
        redirect_to :back, :notice => "<b>#{User.find(params[:id]).first_name} #{User.find(params[:id]).last_name}</b> moved to <b>#{newgroup.name}</b>"
      else
        redirect_to :back, :alert => "Unable to change group."
      end

    else
      newgroup = Group.find_by_id(params[:group][:id])
      relation = GroupRelation.create(group_id: newgroup.id, user_id: params[:id], project_id: current_user.current_project)
      if relation.save
        redirect_to :back, :notice => "<b>#{User.find(params[:id]).first_name} #{User.find(params[:id]).last_name}</b> moved to <b>#{newgroup.name}</b>"
      else
        redirect_to :back, :alert => "Unable to change group."
      end
    end

  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:notice] = "Group updated successfully"
      redirect_to(:action => 'index')
    else
      flash[:error] = "Group could not be updated"
      render('edit')
    end
  end

  def remove
    @group = Group.find(params[:id])
    @group.destroy
    if @group.save
      flash[:notice] = "Group Deleted"
    else
      flash[:error] = "Group could not be deleted"
    end
    redirect_to(:action => 'index')
  end

  def show
    @group = Group.find(params[:id])
    authorize current_user
  end

  def leave
    group = Group.find(params[:id])
    authorize current_user
    set_current_users_instance_variables
    if !group.nil?
      if group.group_relations.where(status: 2).size <= 2
        # Delete the group
        group.destroy
        # Delete relation for current user
        group.group_relations.each { |relation| relation.destroy }
      else
        current_user.group_relations.find_by(group_id: group.id).destroy
      end
      # Delete relation for user
      # group.users.each do |user|
      #   ChangeMailer.send_change_message(user.email).deliver if user!=current_user
      # end
      flash[:notice] = "Group Relation successfully reset."
    else
      flash[:error] = "Unable to reset Group Relation."
    end
    redirect_to :back
  end

  def confirm
    group = Group.find(params[:id])
    authorize current_user
    project = Project.find_by_id(current_user.current_project)
    allowed_group_size = project.group_size

    if GroupRelation.find_by(user_id: current_user.id, group_id: group.id).status == 1
      requested = GroupRelation.find_by(user_id: current_user.id, group_id: group.id)
      requested.status = 2
      redirect_to root_path
      requested.save ? flash[:notice] = "Successfully added to group: <b>#{group.name}</b>"  : flash[:notice] = "There was a problem, try again"

    elsif GroupRelation.find_by(user_id: current_user.id, group_id: group.id).status == 2
      requested = GroupRelation.find_by(group_id: group.id, status:0)
      requested.status = 2

      # "other_requests" are request excluding the one being confirmed (for the same project)
      other_requests = GroupRelation.where(user_id: current_user.id, project_id: project.id) - GroupRelation.where(user_id: current_user.id, group_id: group.id)

      # we want to delete all the "other_requests" since if person confirms group then
      # all the other requests should disappear
      other_requests.each do |other_request|
        other_request.destroy
      end
      redirect_to root_path
      requested.save ? flash[:notice] = "Successfully added to group: <b>#{group.name}</b>"  : flash[:notice] = "There was a problem, try again"
    else
      redirect_to root_path, flash[:error] = "Your Professor specified this project is an individual task. If this is incorrect, please contact your professor."
    end
  end

  def request_join
    group = Group.find(params[:id])
    project = Project.find_by_id(current_user.current_project)
    authorize current_user
    set_current_users_instance_variables
    allowed_group_size = project.group_size
    if !GroupRelation.find_by(group_id:group.id, user_id:current_user.id, status:2).nil?
      flash[:error] = "You are already in a group"
    elsif allowed_group_size >= group.users.size
      #create relation for current user
      current_user_relation = GroupRelation.create(user_id: current_user.id,
                                                   project_id: @myproject.id, status: 0, group_id: group.id)
      flash[:notice] = "Sent request to join <b>#{group.name}</b> "
      # group.users.each do |user|
      #   ChangeMailer.send_change_message(user.email).deliver
      # end
    else
      flash[:error] = "<b>#{group.name}</b> is full"
    end
    redirect_to users_path
  end

  def send_request
    user = User.find(params[:id])
    authorize user
    set_current_users_instance_variables

    if @current_group_size >= @allowed_group_size
      flash[:error] = "Unable to send request, you have too many pending requests."
    else
      @allowed_group_size > 2 ? group_namer("random", @myproject) : group_namer("partner", @myproject)
      if @mygroup.nil?
        newgroup = Group.create(name: @groupname, course_id: @mycourse.id, project_id: @myproject.id)
        #create relation for current user
        current_user_relation = GroupRelation.create(user_id: current_user.id, project_id: @myproject.id, status: 2, group_id: newgroup.id)
      else
        newgroup = Group.find_by_id(@mygroup)
      end
      # create relation for user who is being requested (status=1, requested)
      user_relation = GroupRelation.create(user_id: user.id, project_id: @myproject.id, status: 1, group_id: newgroup.id)
      # ChangeMailer.send_change_message(user.email).deliver
      flash[:notice] = "Requested <b>#{user.first_name} #{user.last_name}</b> to your group: <b>#{newgroup.name}</b> "
    end
    redirect_to users_path
  end

  def disband
    group = Group.find(params[:id])
    groupname = group.name
    authorize current_user
    set_current_users_instance_variables

    group.group_relations.each do |relation|
      relation.destroy
    end

    if group.destroy
      flash[:notice] = "#{groupname} has been disbanded."
    else
      flash[:error] = "Unable to disband #{groupname}."
    end
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :project_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def group_namer(namegen, project)
    case namegen
    when "number"
      @groupname = "Team #{Group.where(project_id: project.id).size + 1}"
    when "random"
      @groupname = "Team #{Faker::Team.random.titlecase}"
    when "creature"
      @groupname = "Team #{Faker::Team.creature.titlecase}"
    when "color"
      @groupname = "Team #{Faker::Commerce.color.titlecase}"
    when "gamer"
      @groupname = "#{Faker::Hacker.gamer.titlecase}"
    when "partner"
      @groupname = "#{current_user.first_name} and #{User.find(params[:id]).first_name}"
    end
    return @groupname
  end

  def phone_generator(user)
    phone = rand.to_s[2..11]
    user.phone = phone
    user.save
  end

  def availability_generator(user)
    case (1 + rand(6))
    when 1..2
      day1  = Faker::Time.between(7.days.ago, Time.now).strftime('%A')
      day2  = Faker::Time.between(7.days.ago, Time.now).strftime('%A') until (day2 != day1) && (!day2.nil?)
      availability = day1 + " or " + day2
    when 3
      day1  = Faker::Time.between(7.days.ago, Time.now).strftime('%A')
      day2  = Faker::Time.between(7.days.ago, Time.now).strftime('%A') until (day2 != day1) && (!day2.nil?)
      availability = day1 + " and " + day2
    when 4
      availability = Faker::Time.between(7.days.ago, Time.now).strftime('%A')
    when 5
      availability = "Weekend"
    when 6
      availability = "Weekday"
    end
    case (1 + rand(4))
    when 1
      availability = availability + " nights"
    when 2
      availability = availability + " evenings"
    when 3
      availability = availability + " mornings"
    when 4
      availability = availability + " anytime"
    end
    user.availability = availability
    user.save
  end

  def description_generator(user)
    description = Faker::Hacker.say_something_smart
    user.description = description
    user.save
  end

  def avatar_generator(user)
    avatar = File.open(Dir.glob(File.join(Rails.root, 'sample', '*')).sample)
    user.avatar = avatar
    user.save
  end

  def eval_generator(user)
    user.groups.each do |group|
      group.group_relations.each do |relation|
        if user.id != relation.user_id
          eval = Evaluation.create(quality: (50 + rand(50)), effort:(50 + rand(50)), reliability:(50 + rand(50)), comments: Faker::Hacker.say_something_smart)
          eval_relation = EvalRelation.create(user_id:user.id, reviewer_id: relation.user_id, group_id: group.id, project_id: group.project_id, evaluation_id: eval.id)
        end
      end
    end
  end

  def set_current_project_course(user, project, course)
    user.current_project = project.id
    user.current_course = course.id
    user.save
  end

  def set_confirm_add_to_group(user)
    requested = GroupRelation.where(user_id: requested?(user).id, group_id: @mygroup.id)
    requested.status = 2
    requested.save
  end

end

app/views/groups/_form.html.erb
<div style="line-height:2; max-width:400px;">
	<%= f.label 'Group Name: ' %>
	<%= f.text_field(:name, class: "form-control") %><br/>
	<%= f.submit("Save Group", class: 'btn btn-primary') %>
</div>

app/views/groups/_group_render.erb
<% count = 0 %>
<% @myproject.groups.collect(&:name).include?('Team 10')||@myproject.groups.collect(&:name).include?('Team 11') ? groups = @myproject.groups.uniq : groups = @myproject.groups.order(:name).uniq %>
<% if @group.nil?%>
<% groups.each do |group| %>
<% count += 1 %>
<% if @group!= group && (group.group_relations.size < @myproject.group_size) %>
<table class="table table-condensed table-hover">
	<% @group = Group.find(group) %>
	<tr class="info active" id="tr-<%= count%>">
		<th class='collapsable'></th><th class='collapsable'></th><th><h3><%= link_to @group.name, @group %></h3></th><th class='collapsable'></th></th>
		<td style="text-align:right"><%= link_to("<span class=\"glyphicons glyphicons-send\"></span>&nbsp;&nbsp;Request to join".html_safe, request_join_group_path(@group.id), class: 'btn btn-success')%></td><th class='collapsable'></th>
	</tr>
	<tr>
		<td class='collapsable'></td>
		<td class='collapsable'></td>
		<td style="font-weight:bold;">Name</td>
		<td class='collapsable' style="font-weight:bold;">Email</td>
		<td class='collapsable' style="font-weight:bold;">Availability</td>
		<td style="font-weight:bold;text-align:right;">Status</td>
		<td></td>
	</tr>
	<!-- each table row of the members of the group -->
	<% members = group.users.order(:last_name).uniq %>
	<% members.each do |user| %>
	<% if GroupRelation.find_by(user_id: user.id, group_id: @group.id).status == 2 %>
	<tr>
		<td class='collapsable'></td>
		<td class='collapsable'><%= link_to (image_tag (user.avatar.url), class:"img-rounded"), user %></td>
		<td id='name'><%= link_to "#{user.first_name} #{user.last_name}", user %> </td>
		<td class='collapsable'><%= user.email %></td>
		<td class='collapsable'><%= user.availability %></td>
		<td style="text-align:right">Confirmed&nbsp;&nbsp;<span class="glyphicons glyphicons-ok" style="color:green; font-size:20px;"></span></td>
		<% else %>
		<tr class = "active" style= "opacity: 0.6;"><td></td>
		<td class='collapsable'><%= link_to (image_tag (user.avatar.url), class:"img-rounded"), user %></td>
		<td><%= link_to "#{user.first_name} #{user.last_name}", user %> </td>
		<td class='collapsable'><%= user.email %></td>
		<td class='collapsable'><%= user.availability %></td>
		<td style="text-align:right">Pending </td></tr>
		<% end %>
		<% end %>
	</table>
	<% end %>

	<% end %>
	<% if count==0 %></div>
		<% msg ="<b>Sorry, it looks like there aren't any groups available yet!"%>
		<div class="alert alert-info"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= content_tag :div, msg.html_safe, id: "flash_success" %></div>
	<% end %>
<% else %></div>
<% msg ="<u><a href=\"/groups/#{@group.id}\">#{@mygroup.name}</u></a> is full.  <br>You have <span style= 'font-size: 18px; font-weight:bold;'>#{@group.users.size}</span> members out of the <span style= 'font-size: 18px; font-weight:bold;'>#{@group.project.group_size}</span> members allowed in your group."%>
<div class="alert alert-info"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<%= content_tag :div, msg.html_safe, id: "flash_success" %></div>
<% end %>

app/views/groups/_mygroups.html.erb
<br><div style="padding: 15px  15px 15px 15px; background-color: #f9fbfb;border: 1px solid #d6d6d6; border-radius: 4px;-webkit-box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);"><h1 style="font-size:40px; font-weight:bold;"><center>Current Groups</center></h1><br><br>
  <%current_user.projects.each do |project|%>
	  <% @myproject = project %>
		<% if @mygroup = current_user.groups.find_by(project_id: project.id)%>
		<%if @mygroup.group_relations.find_by(user_id: current_user.id).status == 2 %>
		<div style="padding: 10px  15px 10px 15px; background-color: #f9fbfb;
  border: 1px solid #d6d6d6; border-radius: 4px;-webkit-box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);">
		<%= render 'groups/profile', project: @myproject, group: @mygroup  %></div><br>
		     <% end %><% end %><% end %></div>

app/views/groups/_professor_groups.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2><span class="glyphicons glyphicons-group"></span>&emsp;Groups for
     <span class="col-sm-3" style="float:none"><%= render "layouts/buttons/course_select"%></span>
     <span class="col-sm-3" style="float:none"><%= render "layouts/buttons/project_select"%></span></h2>
   </div>
    <div class="panel-body">
      <div class="col-sm-6">
        <%= link_to '#', class: 'export-popover btn btn-primary', data: {placement:'bottom', trigger:'focus' } do %>
            Export Table
        <% end %>
      </div>
      <div class="col-sm-4">
        Group Size: <%= @myproject.group_size %><br>
        <% @myproject.group_size.times do |o|%>
        <%=  link_to "<span class=\"glyphicons glyphicons-user\" style=\"font-size:14px;\"></span>".html_safe, reduce_groupsize_project_path(@myproject.id), class: "groupsize_changes"%>
        <% end %>
        <% if @myproject.group_size < 7 %>
        <%=  link_to "<span class=\"glyphicons glyphicons-plus\" style=\"font-size:14px;\"></span>".html_safe, increase_groupsize_project_path(@myproject.id), style: "color:green"%>
        <% else %>
        <%=  link_to "<span class=\"glyphicons glyphicons-minus\" style=\"font-size:14px;\"></span>".html_safe, reduce_groupsize_project_path(@myproject.id), style: "color:red"%>
        <% end %>
      </div>
      <div class="col-sm-2">
        <%= link_to "Autogroup&nbsp;&nbsp;<span class=\"glyphicons glyphicons-random\"></span>".html_safe, autogroup_project_path(@myproject.id), id:"autogroup-btn", class:"btn btn-info"%>
      </div>
    </span>
    <% (@myproject.groups.collect(&:name).include?("Team 10") || @myproject.groups.include?("Team 11")) ? ids = Group.where(project_id: @myproject) : ids = Group.where(project_id: @myproject).order(:name).uniq%>
    <% ids.each do |group| %>
  <% @group = Group.find(group) %></div>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4><%= link_to @group.name, @group %><%=  link_to "Delete #{@group.name} &nbsp;<span class=\"glyphicons glyphicons-remove-2\"></span>".html_safe, disband_group_path(group), data: { confirm: "Are you sure? This will permanently delete this group and you will lose all evaluation information."},  id: "disband-group-btn", style:"float:right", class: "btn-danger btn-xs"%></h4>
    </div>
    <table class="table table-condensed table-hover" id="group_table" align="center">
      <% @group.users.each do |user| %>
      <tr>
        <% @user = user %>
        <td id='name'><%= link_to "#{user.first_name} #{user.last_name}", user %></td>
        <td class='collapsable'><%= user.email %></td>
        <td>
          <% if GroupRelation.find_by(user_id: user.id, group_id: @group.id).status != 2 %>
          Request Pending
          <% else %>
          Confirmed <span class="glyphicons glyphicons-ok-2" style="color:green; font-size:20px; margin:0px"></span>
          <% end %>
        </td>
        <td class='collapsable'><%= render 'layouts/buttons/team_select', user: @user%></td>
      </tr>
    <% end %></table>
    <% end %> </div><button type="button" class="btn btn-danger btn-xs"><%= link_to "<span class=\"glyphicons glyphicons-warning-sign\"></span>&nbsp;&nbsp;Reset Groups".html_safe, clear_partnerships_project_path(@myproject.id), style:"color:white", id: "disband-all-btn" %></button>    </div>

app/views/groups/_profile.html.erb
<% if @group.nil? %>
    <div class="panel panel-info">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span style="font-size:20px; font-weight:bold;">Sorry,</span> it looks like you don't
            have a <%= @myproject.group_size == 2 ? "partner" : "group"%> yet for <%= Project.find(current_user.current_project).name %>
    </div>
<% else %>
    <% !@group.name.nil? ? groupname = @group.name : groupname = @group.users.pluck(:first_name).to_sentence %>
    <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <span style="font-size:18px; font-weight:bold;">
        <%= link_to '#', data: { toggle: 'modal', target: "#show-#{@group.id}"} do %>
                <%= @group.name %>
        <% end %></span>
                        <%= render template: "groups/modals/show", locals: {group: @group}%></td>
                    </div>
    <% if current_page?(root_path)%>
        <%= link_to "<span class=\"glyphicons glyphicons-remove\"></span>&nbsp;&nbsp;<b>Leave Group</b>".html_safe, leave_group_path(@group), data: { confirm: "Are you sure you want to leave the group #{@group.name}?"},  class: "btn btn-danger btn-xs", style: "float:right" %>
        </div>
        <div class="panel-body">
            <div class="pull-left text-left">
            <span style="font-weight:bold;">Project: </span><%= @group.project.name%><br>
            <span style="font-weight:bold;">Course: </span><%= ((@group.project.courses)&(current_user.courses))[0].course_title%></span>
        </div>
            <div class="pull-right">
                <span style="font-weight:bold;">Partnership Deadline:</span>
                <%= (@group.project.partnership_deadline.nil? || @group.project.partnership_deadline == "") ? "Not Specified" : @group.project.partnership_deadline.strftime("%m/%d/%y") %>
                <br>
                <span style="font-weight:bold;">Evaluation Deadline:</span>
                <%= (@group.project.evaluation_deadline.nil? || @group.project.evaluation_deadline == "") ? "Not Specified" : @group.project.evaluation_deadline.strftime("%m/%d/%y") %>
            </div>
    <% else %> </div>
    <% end %>
    <table class="table table-condensed table-hover">
        <tr class="active" >
            <td style="font-weight:bold;">Name</td>
            <% if current_page?(root_path)%>
            <td class='collapsable' style="font-weight:bold;">Email</td>
            <td style="font-weight:bold;">Phone</td>
            <% end %>
            <td style="font-weight:bold;">Status</td>
            <td style="font-weight:bold;">Evaluated?</td></tr>
            <% members = @group.users.order(:last_name).uniq %>
            <% members.each do |user| %>
            <% @user = user %>
            <tr style="<%= (user.group_relations.find_by(group_id: @group.id).status != 2) ? 'background-color:eee; opacity: 0.6;' : '' %>">
                <td style="font-size:12px;">
                    <%= link_to '#', data: { toggle: 'modal', target: "#show-#{user.id}"} do %>
                <%= user.first_name %> <%= user.last_name %>
                <% end %>
                        <%= render template: "users/modals/show", locals: {user: @user}%></td>
                <% if current_page?(root_path)%>
                    <td style="font-size:12px;" class='collapsable'><%= user.email %></td>
                    <td style="font-size:12px;" class='collapsable'><%= number_to_phone(user.phone, area_code: true) if current_user.phone %></td>
                    <% end %>
                    <td style="font-size:12px;" ><%= (user.group_relations.find_by(group_id: @group.id).status == 2) ? 'Confirmed' : 'Requested'%></td>
                    <!-- if group member is yourself -->
                <% if user == current_user %>
                    <td style="font-size:12px;" >That's you!</td>
                    <!-- If you sent request or are requested a member -->
                <% elsif (user.group_relations.find_by(group_id: @group.id).status == 1 || current_user.group_relations.find_by(group_id: @group.id).status == 1) %>
                    <td style="font-size:12px;" >Request Pending</td>
                    <!-- If you sent a request to join this group -->
                <% elsif (user.group_relations.find_by(group_id: @group.id).status == 0 &&
                    current_user.group_relations.find_by(group_id: @group.id).status == 2) %>
                    <td style="font-size:12px;" >Sent <%=@group.name%> a request</td>
                    <!-- if they're confirmd member of group -->
                <% else %>
                    <!-- show either eval form or "evaluation completed" depending if it's complete -->
                    <% evaluated_left = User.find(@group.users.collect(&:id) - @group.eval_relations.where(reviewer_id:current_user.id).collect(&:user_id)) %>
                    <td style="font-size:12px;">
                        <% if evaluated_left.include?(user) %>
                            <span class="btn btn-primary btn-xs" data-toggle="modal" data-target="#evaluate-<%= @group.id%>">Evaluate</span>
                            <% else %>
                            Completed
                            <% end %>
                        <%= render template: "evaluations/modals/new-evaluation", locals: {group: @group}%>
                        </td>
                <% end %>
            </tr>
            <% end %>
        </table>
  
    <% end %>
</div>

app/views/groups/index.html.erb
<% case current_user.role %>
<% when 0 %>
	<%= render 'groups/student_find_group' %>
<% when 1 .. 3 %>
	<%= render'groups/professor_groups' %>
<% end %>

app/views/groups/show.html.erb
<% @myproject = Project.find(current_user.current_project) %>
    <div class="panel panel-default">
        <!-- Default panel contents -->
      <div class="col-xs-4">
    <h2><% (@myproject.group_size == 2) ? 'Partnership' : 'Group' %></h2>
    <h3><%=@group.name%></h3>


    <h4>Project: <%=@myproject.name%></h4>
    <h4>Course: <%= @myproject.courses.collect(&:course_title).uniq.to_sentence%></h4>
    <%= link_to "<span class=\"glyphicons glyphicons-pencil\"></span>&nbsp;&nbsp;Edit Group Name".html_safe,  {action: 'edit'}, class: "btn btn-success btn-xs" if (current_user.groups.include? @group) || (current_user.role != 0) %>
    <%= link_to "<span class=\"glyphicons glyphicons-remove\"></span>&nbsp;&nbsp;<b>Leave Group</b>".html_safe, leave_group_path(@group), data: { confirm: "Are you sure you want to leave the group #{@group.name}?"},  class: "btn btn-danger btn-xs" %>
    </div>
    <div class="col-xs-8">
  <h2><% @myproject.group_size != 2 ? 'Group Members' : '' %></h2>
  <table class="table table-condensed table-hover">
    <tr class="active">
    <th>Name</th>
    <th class='collapsable'>Email</th>
    <th>Status</th>
    <th>Phone</th>
  </tr>
    <% @group.users.each do |user| %>
    <% confirmed = GroupRelation.find_by(user_id: user.id, group_id: @group.id).status == 2 %>
      <% if confirmed %>
      <tr style= "<%= 'background-color:eee; opacity: 0.6;' if GroupRelation.find_by(user_id: user.id, group_id: @group.id).status != 2 %>">
        <% else %>
        <tr>
          <% end %>
          <td><%= link_to "#{user.first_name} #{user.last_name}", user %></td>
          <td style="font-size:12px;" class='collapsable'><%= user.email %></td>
          <% if current_page?(root_path)%>
          <td style="font-size:12px;" class='collapsable'><%= number_to_phone(user.phone, area_code: true) if current_user.phone %></td>
          <% end %>
          <td><%= confirmed ? 'Confirmed' : 'Request Pending' %></td>
          <td><%= number_to_phone(user.phone, area_code: true) %></td>
        </tr>
        <% end %>
      </table>
    </div>