config/routes.rb
Rails.application.routes.draw do
  resources :reports
  mount Upmin::Engine => '/kayslegion'

  get 'groups/profile'
  get 'users/profile'
  get 'roster', to: 'roster#index'
  get 'playground', to: 'visitors#playground'
  get 'eval_gen', to: 'users#eval_gen'
  get 'phone_gen', to: 'users#phone_gen'
  get 'avatar_gen', to: 'users#avatar_gen'
  get 'avail_gen', to: 'users#avail_gen'
  get 'desc_gen', to: 'users#desc_gen'
  get 'gen', to: 'users#gen'
  post 'courses/csv_import'


  devise_for :users, :controllers => {:registrations => "registrations"}
  root :to => "visitors#index"

  resources :users do
    member do
      get :registrations
      get :sessions
      post :set_current_course
      post :set_current_project
    end
    collection do
      get :desc_gen
      get :avail_gen
      get :avatar_gen
      get :phone_gen
      get :eval_gen
      get :gen

      get :export_ungrouped
      get :export_groups
    end
  end

  resources :groups do
    member do
      get :edit
      post :update
      get :remove
      get :leave
      get :request_join
      get :send_request
      get :disband
      get :show
      get :update
      get :confirm
      post :update_relation
    end
    collection do
    end
  end

  resources :courses do
    member do
      get :edit
      get :show
      post :update

    end
    collection do
      get :csv_import
    end
  end

  resources :projects do
    member do
      get :edit
      post :update
      get :remove
      get :reduce_groupsize
      get :show
      get :increase_groupsize
      get :autogroup
      post :autogroup
      get :clear_partnerships
      post :set_current_project
    end
    collection do
    end
  end

  resources :grouprelations do
    member do
      get :edit
      post :update
      get :remove
    end
    collection do
    end
  end
  resources :evaluations do
    member do
      get :edit
      post :update
      get :remove
    end
    collection do
      get :export_evals
      get :export_eval_summary
    end
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "sign_out", to: "devise/sessions#destroy"
    get "edit", to: "devise/registrations#update"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :groups, :through => :group_relations
  has_many :users, :through => :group_relations
  has_many :evaluations, :through => :eval_relations
  has_many :courses, :through => :project_relations
  belongs_to :evaluation
  belongs_to :user
  belongs_to :group
  belongs_to :course
  has_many :group_relations
  has_many :project_relations
  has_many :eval_relations
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include UsersHelper, GroupsHelper

  def index
    @projects = Project.all
  end

  def create
    if params[:courses]
      # make one project with lots of relations (project belonging to multiple courses)
      if params[:limit_scope]
        @project = Project.new(project_params)
        @project.save
        params[:courses].each do |course|
          relation = ProjectRelation.create(course_id: course, project_id: @project.id)
          relation.save
        end
        # make many projects with one relation each (individuals with identical)
      else
        params[:courses].each do |course|
          @project = Project.new(project_params)
          @project.save
          relation = ProjectRelation.create(course_id: course, project_id: @project.id)
          relation.save
        end
        if @project.save
          current_user.current_project = @project.id
          current_user.current_course = params[:courses][0]
          current_user.save
        end
      end
      flash[:notice] = "Project Created"
      redirect_to :back
    else
      flash[:alert] = "You must choose a Course to add this project to."
      redirect_to :back
    end
  end

  def reduce_groupsize
    @project = Project.find(params[:id])
    if @project.group_size > 2
      @project.group_size -= 1
      if @project.save
        flash[:notice] = "Size Reduced to #{@project.group_size}"
      end
    else
      flash[:error] = "Group size is too small, it could not be reduced"
    end
    redirect_to :back
  end

  def increase_groupsize
    @project = Project.find(params[:id])
    if @project.group_size < 7
      @project.group_size += 1
      if @project.save
        flash[:notice] = "Size Increased to #{@project.group_size}"
      end
    else
      flash[:error] = "Group size is too large, it could not be increased"
    end
    redirect_to :back
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      if ProjectRelation.find_by(project_id: @project.id).nil?
        relation = ProjectRelation.create(course_id: params[:project][:course_id], project_id: @project.id)
        relation.save
      else
        if !params[:project][:course_id].nil?
          ProjectRelation.find_by(project: @project.id).update_attributes(course_id: params[:project][:course_id], project_id: @project.id)
        end
      end
      flash[:notice] = "Project updated successfully"
    redirect_to courses_path
    else
      flash[:error] = "Project could not be updated"
    redirect_to courses_path
    end
  end

  def autogroup
    students, groups = [], []
    @project = Project.find(params[:id])
    @courses = @project.courses
    @courses.each do |course|
      course.users.each do |user|
      if User.find(user).role == 0 && GroupRelation.where(user_id: user, project_id: @project).empty?
        students.push(user)
      end
    end
    end
    while !students.empty?
      name = group_namer('number', @project)
      newgroup = Group.create(name: name, project_id: @project.id)
      students.sample(@project.group_size).collect(&:id).each do |student|
        GroupRelation.create(group_id: newgroup.id, user_id: student, project_id: @project.id)
        groups.push(student)
        students.delete_if{ |student| groups.include?(student.id)}
      end
    end

    flash[:notice] = "Groups have been randomly assigned for <b>#{@project.name}</b>"
    redirect_to groups_path
  end


  def remove
    @project = Project.find(params[:id])
    @project.destroy
    ProjectRelation.where(project_id: params[:id]).each do |relation|
      relation.destroy
    end
    GroupRelation.where(project_id: params[:id]).each do |relation|
      relation.destroy
    end
    Group.where(project_id: params[:id]).each do |relation|
      relation.destroy
    end
    if @project.save
      flash[:notice] = "Project Deleted"
    else
      flash[:error] = "Project could not be deleted"
    end
    redirect_to courses_path
  end

  def clear_partnerships
    authorize current_user
    set_current_users_instance_variables
    if !@myproject.nil?
      Group.where(project_id: @myproject).each do |proj|
        proj.destroy
      end
      GroupRelation.where(project_id: @myproject).each do |proj|
        proj.destroy
      end
      flash[:notice] = "All Groups and Partnerships were cleared."
    else
      flash[:error] = "Unable to clear group relations."
    end
    redirect_to groups_path
  end


  private

  def project_params
    params.require(:project).permit(:name,:course_id, :group_size, :allow_repeat, :partnership_deadline, :evaluation_deadline)
  end

end

app/views/projects/_courseloop.html.erb
<% @empty_courses.uniq.each do |course| %>
	<div class="panel-heading"><b><%= course.course_title%></b>
	</div>
	<table class="table">
	<% if course.projects.empty? %>
		<tr style= "background-color:#ED8080; width:100% " class= "btn alert-danger" data-toggle="modal" data-target="#create-<%= course.id%>">
		<td>	
		    <span class="glyphicons glyphicons-warning-sign"></span>
		    <span style="font-size:18px;">&ensp;Alert:</span></span>
		    <span style="font-size:13px;">There is no active project for <%= course.course_title %>.<br>
        Students are not able to partner up.</span>
        <% @notifications = true %>
    	<%= render template: "projects/modals/new-project", locals: {course: @course}%>
		</td>
	</tr>
	</table>
	<% else %>
		<%= render "projects/projectloop", course: @course %>
		<tr></tr>
	</table>
	<% end %>
<% end %>

app/views/projects/_form.html.erb
<div>
	<% project = Project.find_by_id(@project.id) if !@project.nil?%>
	<% repeat = project.allow_repeat if !@project.nil? %>

	<table style="width:100%">
		<tr>
			<td><span class="glyphicons glyphicons-pushpin"></span></td>
			<td><%= f.label 'Project Name: ' %></td>
			<td colspan='2'><%= f.text_field(:name, class: "form-control") %></td>
		</tr>
	</table>
	
	<table style="width:100%">
		<% oneweeklater = Time.now + (7*24*60*60) %>
		<tr>
			<td><span class="glyphicons glyphicons-calendar"></span></td>
			<td><%= f.label 'Partnership Deadline:'%></td>
			<td><input type="text" name="partnership_deadline" value="<%= oneweeklater.strftime("%m/%d/%Y")%>"></td>
		</tr>
			<% twoweekslater = oneweeklater + (7*24*60*60) %>
		<tr>
			<td><span class="glyphicons glyphicons-calendar"></span></td>
			<td><%= f.label 'Evaluation Date:'%></td>
			<td><input type="text" name="evaluation_deadline" value="<%= twoweekslater.strftime("%m/%d/%Y")%>"></p></td>
		</tr>
	</table>
	<table style="width:100%">
		<tr>
			<td><span class="glyphicons glyphicons-group"></span></td>
			<td><%= f.label 'Group Size of Project: ' %></td>
			<td><%= f.select :group_size, [['2 people','2'], ['3 people','3'], ['4 people','4'], ['5 people','5'], ['6 people','6']], {}, {class: "form-control"} %></td>
		</tr>
	</table>

<input type="checkbox" name="courses[]" checked='true' value="<%= @course.id %>" hidden='true'>

	<table style="width:100%;padding:1px;margin-top:15px">
		<tr>
			<td><span class="glyphicons glyphicons-retweet-2"></span></td>
			<td colspan='2'> <b>Allow students to have repeats for this project?</b></td>
		</tr>
	</table>
	<table style="width:100%">
		<tr>
			<td style="padding:5px 10px 5px 10px;text-align:right; <%= 'background:#ddd' if repeat == true %>"><%= f.radio_button :allow_repeat, true, checked:((repeat == true) || (repeat==nil)) %> </td>
			<td style="padding:5px 10px 5px 10px;<%= 'background:#ddd' if repeat == true %>"><span class="glyphicons glyphicons-ok-2" style="color:green;"></span>&ensp;Allow Repeats</td>
		</tr>
		<tr>
			<td style="padding:5px 10px 5px 10px;text-align:right; <%= 'background:#ddd' if repeat == false %>"><%= f.radio_button :allow_repeat, false, checked: (repeat == false) %> </td>
			<td style="padding:5px 10px 5px 10px;<%= 'background:#ddd' if repeat == false %>"><span class="glyphicons glyphicons-ban" style="color:red;"></span>&ensp;Restrict Repeats</td>
		</tr>
	</table>
		
		
		
	</div>

app/views/projects/_projectloop.html.erb
<% course.projects.each do |project| %>
<tr>
	<td style="padding:1px;">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<%= project.name %>
	</td>
	<td>
		<%=  link_to remove_project_path(project), style: "float:right;", class: "btn btn-danger btn-xs" do %>Delete<% end %> 
	</td>
</tr>
<% end %>

app/views/projects/_single.html.erb
<span style="font-size:40px; font-weight:bold;"><span class="glyphicons glyphicons-pushpin"></span>&emsp;Projects</span><br>

<table class="table" style="max-width:1200px;" align="center">
<% @empty_courses = current_user.courses%>
<% @empty_courses.each {|course| @empty_courses = @empty_courses.unshift(course) if course.projects.empty?} %>
<% @empty_courses.uniq.each do |course| %>
<tr style='background-color:#eee;'>
    <th colspan="7" style="height:20px; padding:7px 10px 3px 10px;"><span style="font-size:17px; font-weight:bold;"><%= course.course_title%></span></th>
    <th style="height:20px; padding:7px 10px 3px 10px;"><%=  link_to "<span class=\"glyphicons glyphicons-plus\"></span>&nbsp;&nbsp;Add New Project".html_safe,  {action: 'new', controller: 'projects', id: course}, class: "btn btn-primary btn-xs", id: "add-new-project", style: "float:right;margin-bottom:10px;" %></th>
</tr>
<tr>
	<th></th>
	<th colspan="2" style="padding:7px 10px 3px 10px; font-size:12px;"><span class="glyphicons glyphicons-pushpin"></span>&emsp;Project Title</th>
	<th class='collapsable' style="padding:7px 10px 3px 10px; font-size:12px;"><span class="glyphicons glyphicons-group"></span>&emsp;Group Size</th>
	<th class='collapsable' style="padding:7px 10px 3px 10px; font-size:12px;"><span class="glyphicons glyphicons-retweet-2"></span>&emsp;Repeats?</th>
	<th class='collapsable' style="padding:7px 10px 3px 10px; font-size:12px;"><span class="glyphicons glyphicons-calendar"></span>&emsp;Partnership Deadline</th>
	<th class='collapsable' style="padding:7px 10px 3px 10px; font-size:12px;"><span class="glyphicons glyphicons-calendar"></span>&emsp;Evaluation Deadline</th>
</tr></b>
  <% if course.projects.empty? %>
  <tr style= "background-color:#ED8080; "><td colspan="6" style= "padding:0px;"><%=  link_to (new_project_path(id: course)), style: "color:#fff; text-align:left; width:100%; padding:11px;", class: "btn btn-danger" do %><b>Alert:</b> There is no active project for this course. Students are not able to partner up. <% end %> </tr></td>
  <% end %>
	<% course.projects.each do |project| %>
		<tr><% if project.id != 0 %>
			<td></td>
	  	<th colspan='2' style="padding:10px 10px 0px 10px;">
	  	<%= form_for(:project, url: {action: 'update', id: project.id}, html: {style: "margin-bottom:0em;"}) do |f| %>
			<%= f.text_field :name, {onchange: 'this.form.submit();', value: project.name, style: "font-size: 14px; width:100%;"} %>
			<% end %>
		</th>
		<th class='collapsable' style="padding:10px 10px 0px 10px;">
		<% project.group_size.times do |o|%>
	    	<%=  link_to "<span class=\"glyphicons glyphicons-user\"></span>".html_safe, reduce_groupsize_project_path(project.id), class: "groupsize_changes"%>
	    <% end %>
	    <% if project.group_size < 7 %>
	    	<%=  link_to "<span class=\"glyphicons glyphicons-plus\"></span>".html_safe, increase_groupsize_project_path(project.id), style: "color:green"%>
	    	<% end %>
		</th>
			
		<td class='collapsable' style="padding:10px 10px 0px 10px;">
			<%= form_for(:project, url: {action: 'update', id: project.id}, html: {style: "margin-bottom:0em;"})  do |f| %>
			<center><%= project.allow_repeat ? "<span class=\"glyphicons glyphicons-ok-2\" style=\"color:green; font-size:17px;\"></span>".html_safe : "<span class=\"glyphicons glyphicons-ban\" style=\"color:red; font-size:17px;\"></span>".html_safe%>
			<%= f.check_box :allow_repeat, {onclick: 'this.form.submit();', checked: project.allow_repeat} %>
			<% end %></center>
			</td>
		<td class='collapsable' style="padding:7px 10px 3px 10px; font-size:12px;"><center>
			<%= form_for(:project, url: {action: 'update', id: project.id}, html: {style: "margin-bottom:0em;"}) do |f| %>
			<%= f.date_field :partnership_deadline, {onchange: 'this.form.submit();', value: project.partnership_deadline, style: "line-height: 10px;"} %>
			<% end %>
		</center></td>
		<td class='collapsable' style="padding:7px 10px 3px 10px; font-size:12px;"><center>
			<%= form_for(:project, url: {action: 'update', id: project.id}, html: {style: "margin-bottom:0em;"}) do |f| %>
			<%= f.date_field :evaluation_deadline, {onchange: 'this.form.submit();', value: project.evaluation_deadline, style: "line-height: 10px;"} %>
			<% end %>
		</center></td>
		<td style="padding:8px 0px 8px 0px;">
    	 <%=  link_to "<span class=\"glyphicons glyphicons-remove-2\"></span>&nbsp;&nbsp;Delete".html_safe, remove_project_path(project.id), id: "delete-#{project.id}", data: { confirm: "Are you sure you want to delete this project?"}, class: "btn btn-danger btn-sm"%></td>
		</tr>
	<% end %>
<% end %><tr><td colspan="9" style="height:30px; padding:10px 10px 0px 10px;"></td></tr>
<% end %></table>

app/views/projects/index.html.erb
<% if current_user.role !=0 %>
<% @empty_courses = current_user.courses %>
<% @empty_courses.each {|course| @empty_courses = @empty_courses.unshift(course) if course.projects.empty?} %>

<div class="panel panel-default" style="float:left;width:100%">
	<%= render 'projects/courseloop', local: @empty_courses%>
</div>
<% end %>

app/views/projects/modal.html.erb
<!-- Modal -->
<div class="modal fade" id="create-project">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a New Project</h4>
      </div>
      <div class="modal-body">
				<%= form_for :project, url: {action: 'create'}, html: { multipart: true } do |f| %>
					<%= render partial: 'form', locals: {f: f} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       	<%= f.submit("Save Project", id: 'save-project', class: 'btn btn-primary') %>
				<% end %>
      </div>
    </div>
  </div>
</div>